version: '3.0'

services:
  app:
    image: mettoboshi/phpunit
    volumes:
      - ./webapp/php/:/var/www/html
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./webapp/sql/admin/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

volumes:
  mysql: